entity_track.settings:
  type: config_object
  mapping:
    track_enabled_entity_types:
      label: Entity types for which tracking is enabled
      type: sequence
      sequence:
        type: string
    track_enabled_plugins:
      label: Enabled tracking plugins
      type: sequence
      sequence:
        type: string
    track_enabled_base_fields:
      type: boolean
      label: Track referencing base fields
    background_tracking:
      type: boolean
      label: Track entity usage via a background process
